clean up with manual run

diff --git a/.github/workflows/terraform-ci.yml b/.github/workflows/terraform-ci.yml
--- a/.github/workflows/terraform-ci.yml
+++ b/.github/workflows/terraform-ci.yml
@@ -31,7 +31,6 @@ jobs:
         uses: actions/checkout@v4
       
       - name: Run tfsec
-        id: tfsec-container-run
         uses: aquasecurity/tfsec-action@v1.0.3
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
@@ -40,17 +39,17 @@ jobs:
           soft_fail: true
       
       # ----- DEBUG STEPS -----
-      - name: Capture tfsec report
-        id: capture-report
-        run: |
-          echo "${{ steps.tfsec.outputs.tfsec-report.json }}" > ${{ env.TF_DIR }}/tfsec-report.json
+      # - name: Capture tfsec report
+      #   id: capture-report
+      #   run: |
+      #     echo "${{ steps.tfsec.outputs.tfsec-report.json }}" > ${{ env.TF_DIR }}/tfsec-report.json
 
-      - name: List Terraform files
-        run: |
-          ls -la ${{ env.TF_DIR }}
+      # - name: List Terraform files
+      #   run: |
+      #     ls -la ${{ env.TF_DIR }}
 
-      - name: Display Terraform report
-        run: cat ${{ env.TF_DIR }}/tfsec-report.json
+      # - name: Display Terraform report
+      #   run: cat ${{ env.TF_DIR }}/tfsec-report.json
       # -----------------------
 
       # ----- MANUALLY RUN TFSEC -----
@@ -78,19 +77,19 @@ jobs:
           echo "high=$HIGH" >> $GITHUB_OUTPUT
           echo "critical=$CRITICAL" >> $GITHUB_OUTPUT
       
-      - name: Conditionally Fail Pipeline Only in Prod Environment
-        if: ${{ (inputs.env == 'prod') && (fromJSON(steps.tfsec-count.outputs.high) > 0 || fromJSON(steps.tfsec-count.outputs.critical) > 0) }}
-        run: |
-          echo "::warning:: HIGH and/or CRITICAL vulnerabilities detected by tfsec! Blocking production deployment."
-          exit 1
-      
       - name: Conditionally Warn Pipeline in Dev or Test Environments
         if: ${{ (inputs.env == 'dev' || inputs.env == 'tst') && (fromJSON(steps.tfsec-count.outputs.high) > 0 || fromJSON(steps.tfsec-count.outputs.critical) > 0) }}
         run: |
-          echo "::warning:: HIGH and/or CRITICAL vulnerabilities detected by tfsec! Deployment permitted to dev/test environments."
+          echo "::warning:: HIGH and/or CRITICAL issues detected by tfsec! Deployment permitted to dev/test environments."
+
+      - name: Conditionally Fail Pipeline in Prod Environment
+        if: ${{ (inputs.env == 'prod') && (fromJSON(steps.tfsec-count.outputs.high) > 0 || fromJSON(steps.tfsec-count.outputs.critical) > 0) }}
+        run: |
+          echo "::error:: HIGH and/or CRITICAL issues detected by tfsec! Blocking production deployment."
+          exit 1
       
       - name: Conditionally Fail Pipeline in any Other Environment
         if: ${{ (inputs.env != 'dev' && inputs.env != 'tst' && inputs.env != 'prod') && (fromJSON(steps.tfsec-count.outputs.high) > 0 || fromJSON(steps.tfsec-count.outputs.critical) > 0) }}
         run: |
-          echo "::warning:: HIGH and/or CRITICAL vulnerabilities detected by tfsec! Blocking deployment to unknown environment."
+          echo "::error:: HIGH and/or CRITICAL issues detected by tfsec! Blocking deployment to unknown environment."
           exit 1
